# Generated by Django 4.2.7 on 2023-12-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_oferta_usuario_metododepago_juego_compra_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='JuegosPublicados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreJuego', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clasificacion', models.CharField(max_length=100)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('titulodescripcion', models.TextField(null=True)),
                ('descripcion', models.TextField(null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
            options={
                'db_table': 'juegosPublicados',
            },
        ),
    ]
