# Generated by Django 4.2.7 on 2023-12-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_comprasregistradas'),
    ]

    operations = [
        migrations.CreateModel(
            name='slidersPromocionales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
            ],
            options={
                'db_table': 'slidersPromocionales',
            },
        ),
    ]
